### ISSUE TITLE
no matches found via link

### ISSUE THREAD

**Issue by xding2** [amastis/YouTube-data-scraper#1]
I have a little question, when I run

$ python3 Web-Youtube.py --link https://www.youtube.com/watch?v=x9dgZQsjR6s --api 6d5f807e23db210bc254a28be2d6759a0f5f5d99 --comments
zsh: **no matches found:** https://www.youtube.com/watch?v=x9dgZQsjR6s

I already change to my api, above just an example. But no matter I input which link, here will be: **zsh: no matches found:https://www.youtube.com/watch?v=x9dgZQsjR6s**

**Comment by amastis** [comment]
Try wrapping your youtube link and your API key with double quotes while inputting the command.
